// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WFAPlakDukkani.UI.Context;

#nullable disable

namespace WFAPlakDukkani.UI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250520115604_M2_SeedDatalarEklendi")]
    partial class M2_SeedDatalarEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WFAPlakDukkani.UI.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("IndirimOrani")
                        .HasColumnType("float");

                    b.Property<int>("SanatciId")
                        .HasColumnType("int");

                    b.Property<bool>("SatistaMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SanatciId");

                    b.ToTable("Albumler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumAdi = "Aşk Şarkıları",
                            CikisTarihi = new DateTime(2010, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 150m,
                            IndirimOrani = 0.10000000000000001,
                            SanatciId = 1,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 2,
                            AlbumAdi = "Yolla",
                            CikisTarihi = new DateTime(2016, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 175m,
                            IndirimOrani = 0.14999999999999999,
                            SanatciId = 2,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 3,
                            AlbumAdi = "Ele Güne Karşı",
                            CikisTarihi = new DateTime(1992, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 120m,
                            IndirimOrani = 0.20000000000000001,
                            SanatciId = 3,
                            SatistaMi = false
                        },
                        new
                        {
                            Id = 4,
                            AlbumAdi = "İnsanlık Halleri",
                            CikisTarihi = new DateTime(2004, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 135m,
                            IndirimOrani = 0.10000000000000001,
                            SanatciId = 4,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 5,
                            AlbumAdi = "Seni Kendime Sakladım",
                            CikisTarihi = new DateTime(2005, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 140m,
                            IndirimOrani = 0.25,
                            SanatciId = 5,
                            SatistaMi = false
                        },
                        new
                        {
                            Id = 6,
                            AlbumAdi = "Derin",
                            CikisTarihi = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 180m,
                            IndirimOrani = 0.29999999999999999,
                            SanatciId = 6,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 7,
                            AlbumAdi = "30",
                            CikisTarihi = new DateTime(2021, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 250m,
                            IndirimOrani = 0.050000000000000003,
                            SanatciId = 7,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 8,
                            AlbumAdi = "Parachutes",
                            CikisTarihi = new DateTime(2000, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 210m,
                            IndirimOrani = 0.20000000000000001,
                            SanatciId = 8,
                            SatistaMi = false
                        },
                        new
                        {
                            Id = 9,
                            AlbumAdi = "1989",
                            CikisTarihi = new DateTime(2014, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 230m,
                            IndirimOrani = 0.10000000000000001,
                            SanatciId = 9,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 10,
                            AlbumAdi = "Starboy",
                            CikisTarihi = new DateTime(2016, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 190m,
                            IndirimOrani = 0.14999999999999999,
                            SanatciId = 10,
                            SatistaMi = false
                        },
                        new
                        {
                            Id = 11,
                            AlbumAdi = "Divide",
                            CikisTarihi = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 200m,
                            IndirimOrani = 0.20000000000000001,
                            SanatciId = 11,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 12,
                            AlbumAdi = "Aşk Kaç Beden Giyer?",
                            CikisTarihi = new DateTime(2011, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 160m,
                            IndirimOrani = 0.10000000000000001,
                            SanatciId = 12,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 13,
                            AlbumAdi = "Ajda 1990",
                            CikisTarihi = new DateTime(1990, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 110m,
                            IndirimOrani = 0.34999999999999998,
                            SanatciId = 13,
                            SatistaMi = false
                        },
                        new
                        {
                            Id = 14,
                            AlbumAdi = "Sarı Çizmeli Mehmet Ağa",
                            CikisTarihi = new DateTime(1989, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 95m,
                            IndirimOrani = 0.40000000000000002,
                            SanatciId = 14,
                            SatistaMi = false
                        },
                        new
                        {
                            Id = 15,
                            AlbumAdi = "Rengarenk",
                            CikisTarihi = new DateTime(2010, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 145m,
                            IndirimOrani = 0.20000000000000001,
                            SanatciId = 15,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 16,
                            AlbumAdi = "Festival",
                            CikisTarihi = new DateTime(2006, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 170m,
                            IndirimOrani = 0.10000000000000001,
                            SanatciId = 16,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 17,
                            AlbumAdi = "Zeynodisco",
                            CikisTarihi = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 200m,
                            IndirimOrani = 0.14999999999999999,
                            SanatciId = 17,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 18,
                            AlbumAdi = "Maya",
                            CikisTarihi = new DateTime(2018, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 190m,
                            IndirimOrani = 0.25,
                            SanatciId = 18,
                            SatistaMi = false
                        },
                        new
                        {
                            Id = 19,
                            AlbumAdi = "Herşey Sensin",
                            CikisTarihi = new DateTime(2009, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 130m,
                            IndirimOrani = 0.20000000000000001,
                            SanatciId = 19,
                            SatistaMi = false
                        },
                        new
                        {
                            Id = 20,
                            AlbumAdi = "Ben Buraya Çıplak Geldim",
                            CikisTarihi = new DateTime(2012, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 140m,
                            IndirimOrani = 0.10000000000000001,
                            SanatciId = 20,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 21,
                            AlbumAdi = "An",
                            CikisTarihi = new DateTime(2018, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 155m,
                            IndirimOrani = 0.29999999999999999,
                            SanatciId = 21,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 22,
                            AlbumAdi = "Bangır Bangır",
                            CikisTarihi = new DateTime(2015, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 170m,
                            IndirimOrani = 0.10000000000000001,
                            SanatciId = 22,
                            SatistaMi = false
                        },
                        new
                        {
                            Id = 23,
                            AlbumAdi = "Herşey Yolunda",
                            CikisTarihi = new DateTime(2005, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 120m,
                            IndirimOrani = 0.25,
                            SanatciId = 23,
                            SatistaMi = false
                        },
                        new
                        {
                            Id = 24,
                            AlbumAdi = "Rapstar",
                            CikisTarihi = new DateTime(2004, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 140m,
                            IndirimOrani = 0.29999999999999999,
                            SanatciId = 24,
                            SatistaMi = true
                        },
                        new
                        {
                            Id = 25,
                            AlbumAdi = "Kötü İnsanları Tanıma Senesi",
                            CikisTarihi = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fiyat = 160m,
                            IndirimOrani = 0.20000000000000001,
                            SanatciId = 25,
                            SatistaMi = false
                        });
                });

            modelBuilder.Entity("WFAPlakDukkani.UI.Models.Sanatci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SanatciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sanatcilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SanatciAdi = "Sezen Aksu"
                        },
                        new
                        {
                            Id = 2,
                            SanatciAdi = "Tarkan"
                        },
                        new
                        {
                            Id = 3,
                            SanatciAdi = "MFÖ"
                        },
                        new
                        {
                            Id = 4,
                            SanatciAdi = "Teoman"
                        },
                        new
                        {
                            Id = 5,
                            SanatciAdi = "Duman"
                        },
                        new
                        {
                            Id = 6,
                            SanatciAdi = "Berkay"
                        },
                        new
                        {
                            Id = 7,
                            SanatciAdi = "Adele"
                        },
                        new
                        {
                            Id = 8,
                            SanatciAdi = "Coldplay"
                        },
                        new
                        {
                            Id = 9,
                            SanatciAdi = "Taylor Swift"
                        },
                        new
                        {
                            Id = 10,
                            SanatciAdi = "The Weeknd"
                        },
                        new
                        {
                            Id = 11,
                            SanatciAdi = "Ed Sheeran"
                        },
                        new
                        {
                            Id = 12,
                            SanatciAdi = "Hadise"
                        },
                        new
                        {
                            Id = 13,
                            SanatciAdi = "Ajda Pekkan"
                        },
                        new
                        {
                            Id = 14,
                            SanatciAdi = "Barış Manço"
                        },
                        new
                        {
                            Id = 15,
                            SanatciAdi = "Sertab Erener"
                        },
                        new
                        {
                            Id = 16,
                            SanatciAdi = "Kenan Doğulu"
                        },
                        new
                        {
                            Id = 17,
                            SanatciAdi = "Zeynep Bastık"
                        },
                        new
                        {
                            Id = 18,
                            SanatciAdi = "Mabel Matiz"
                        },
                        new
                        {
                            Id = 19,
                            SanatciAdi = "Yalın"
                        },
                        new
                        {
                            Id = 20,
                            SanatciAdi = "Nil Karaibrahimgil"
                        },
                        new
                        {
                            Id = 21,
                            SanatciAdi = "Edis"
                        },
                        new
                        {
                            Id = 22,
                            SanatciAdi = "Gülşen"
                        },
                        new
                        {
                            Id = 23,
                            SanatciAdi = "Athena"
                        },
                        new
                        {
                            Id = 24,
                            SanatciAdi = "Ceza"
                        },
                        new
                        {
                            Id = 25,
                            SanatciAdi = "Sagopa Kajmer"
                        },
                        new
                        {
                            Id = 26,
                            SanatciAdi = "Ezhel"
                        },
                        new
                        {
                            Id = 27,
                            SanatciAdi = "Uzi"
                        },
                        new
                        {
                            Id = 28,
                            SanatciAdi = "Mero"
                        },
                        new
                        {
                            Id = 29,
                            SanatciAdi = "BTS"
                        },
                        new
                        {
                            Id = 30,
                            SanatciAdi = "BLACKPINK"
                        },
                        new
                        {
                            Id = 31,
                            SanatciAdi = "Shakira"
                        },
                        new
                        {
                            Id = 32,
                            SanatciAdi = "Rihanna"
                        },
                        new
                        {
                            Id = 33,
                            SanatciAdi = "Beyoncé"
                        },
                        new
                        {
                            Id = 34,
                            SanatciAdi = "Justin Bieber"
                        },
                        new
                        {
                            Id = 35,
                            SanatciAdi = "Ariana Grande"
                        },
                        new
                        {
                            Id = 36,
                            SanatciAdi = "Imagine Dragons"
                        },
                        new
                        {
                            Id = 37,
                            SanatciAdi = "Linkin Park"
                        },
                        new
                        {
                            Id = 38,
                            SanatciAdi = "Green Day"
                        },
                        new
                        {
                            Id = 39,
                            SanatciAdi = "OneRepublic"
                        },
                        new
                        {
                            Id = 40,
                            SanatciAdi = "Maroon 5"
                        });
                });

            modelBuilder.Entity("WFAPlakDukkani.UI.Models.Yonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Yoneticiler");
                });

            modelBuilder.Entity("WFAPlakDukkani.UI.Models.Album", b =>
                {
                    b.HasOne("WFAPlakDukkani.UI.Models.Sanatci", "Sanatci")
                        .WithMany("Albumler")
                        .HasForeignKey("SanatciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sanatci");
                });

            modelBuilder.Entity("WFAPlakDukkani.UI.Models.Sanatci", b =>
                {
                    b.Navigation("Albumler");
                });
#pragma warning restore 612, 618
        }
    }
}
